### ISSUE TITLE
How to set timeout on a redis cluster client?

### ISSUE THREAD

**Issue by wangfuqiang** [Nordix/hiredis-cluster#88] opened 2022-04-29 09:41 UTC
hey, bjosv
It does not work with command time opt, here's my code
handle_ = redisClusterContextInit();
redisClusterSetOptionAddNodes(handle_, addrs_.c_str());
struct timeval timeout = {0, 5000};
redisClusterSetOptionTimeout(handle_, timeout);
redisClusterConnect2(handle_);
redisReply *reply = (redisReply *)redisClusterCommand(handle_, "GET %s", key.c_str());

Some response still cost more than 5 ms !

**Comment by zuiderkwast** [comment] 2022-04-29 11:12
Maybe you can contribute a solution, either to this project or to https://github.com/redis/hiredis?

**Comment by zjhua68** [comment] 2022-05-30 03:07
The command_timeout in redisClusterContext does not copy to redisContext,  redisSetTimeout which set the redisContext’ timeout in hircluster.c actully set nothing?
So add a call redisContextUpdateCommandTimeout before redisSetTimeout can fix this?

**Comment by bjosv** [comment] 2022-05-30 10:40
@zjhua68 Have you seen this issue in the async api case only, or is it a generic problem?

**Comment by wangfuqiang** [comment] 2022-08-10 07:05
> rojec

hey, what's the diffirence betwwen  hiredis-cluster
 and hiredis ?   now , we are using hiredis-cluster

**Comment by bjosv** [comment] 2022-08-10 07:51
`hiredis-cluster` is a client for [Redis Cluster](https://redis.io/docs/manual/scaling/#redis-cluster-101), where data is sharded across multiple Redis instances. It uses `hiredis` under the hood and handles the calculation of which cluster instance to send the query to. `hiredis-cluster` has a connection to each cluster node, which is provided by `hiredis`.
If you don't have a Redis cluster running `hiredis` will do.

**Comment by wangfuqiang** [comment] 2022-08-10 08:40
> `hiredis-cluster` is a client for [Redis Cluster](https://redis.io/docs/manual/scaling/#redis-cluster-101), where data is sharded across multiple Redis instances. It uses `hiredis` under the hood and handles the calculation of which cluster instance to send the query to. `hiredis-cluster` has a connection to each cluster node, which is provided by `hiredis`. If you don't have a Redis cluster running `hiredis` will do.

hey， our redis are running on cluster mode,  Timeout issus is still not resolved, do u have any idea?

**Comment by bjosv** [comment] 2022-08-10 11:46
See #83

**Comment by bjosv** [comment] 2022-08-11 10:04
I ran some tests myself in both hiredis and hiredis-cluster and the precision is not perfect.
Since hiredis-cluster rely on hiredis, and hiredis relies on a socket config, i.e the kernel, I'm not sure how we could improve this.
We are not running on a real-time system, so I would guess we couldn't get an exact precision.
I'm open to proposals or ideas how to improve it.

Here is the test results of configured timeout vs measured:

**hiredis-cluster 0.8.0**
Configured timeout vs result of 500 queries (Linux x86_64 5.4.0-122-generic):
```
Conf:   Result:
1ms   - Average:    8 ms  Max:   12 ms  Min:    6 ms
5ms   - Average:   12 ms  Max:   16 ms  Min:    8 ms
10ms  - Average:   16 ms  Max:   20 ms  Min:   14 ms
20ms  - Average:   24 ms  Max:   30 ms  Min:   23 ms
50ms  - Average:   56 ms  Max:   60 ms  Min:   52 ms
100ms - Average:  104 ms  Max:  108 ms  Min:  103 ms
500ms - Average:  511 ms  Max:  516 ms  Min:  507 ms
1s    - Average: 1023 ms  Max: 1028 ms  Min: 1009 ms
```

Running similar tests using hiredis only gives similar results:

**hiredis** (on commit 06be7ff312a78f69237e5963cc7d24bc84104d3b)
Configured timeout vs result of 500 queries (Linux x86_64 5.4.0-122-generic):
```
Conf:   Result:
1ms   - Average:    7 ms  Max:   17 ms  Min:    6 ms
5ms   - Average:   11 ms  Max:   16 ms  Min:    8 ms
10ms  - Average:   15 ms  Max:   20 ms  Min:   14 ms
20ms  - Average:   23 ms  Max:   28 ms  Min:   21 ms
50ms  - Average:   55 ms  Max:   60 ms  Min:   54 ms
100ms - Average:  103 ms  Max:  109 ms  Min:  101 ms
500ms - Average:  511 ms  Max:  517 ms  Min:  507 ms
1s    - Average: 1023 ms  Max: 1031 ms  Min: 1014 ms
```

**Comment by zuiderkwast** [comment] 2023-06-16 09:26
Duplicate of #83.

**Closed by zuiderkwast** 2023-06-16 09:26 UTC
